[locations]
# Music library root
# Default is OS-specific default user music folder e.g. ~/Music
# For Windows path with backslash character, use "\\", for example "D:\\Music"
library = "/path/to/music"

# Albums database file
# Default is OS-specific user storage e.g. ~/.config/albums/albums.db
database = "/path/to/albums.db"

# Extensions to scan (if the file type isn't supported by mutagen, there may be errors)
# Defaults to these extensions:
supported_file_types = [".flac", ".mp3", ".m4a", ".wma", ".ogg"]

[options]
# Rescan the library before performing other operations. If the operation is filtered then only
# selected albums will be rescanned. Options:
# "always" - always scan the library so you never need to run "albums scan" but may be slow
# "never" - never automatically scan the library, you must run "albums scan" if it's changed
# "auto" (default) - scan on first run and before "check" or "sync" operations
#rescan = "auto"

# If this option is set, whenever there is an interactive tag fix, there will be a menu option to
# execute this external tagging program. The path of the album will be the first parameter.
#
#tagger = "easytag"

# If this option is set, this will override the default command to open a window for a folder.
#
#open_folder_command = "xdg-open"

##############################################################################
# See documentation for instructions on configuring checks.
# If there is no configuration for a check, it will use defaults (including whether it is enabled).
[checks.disc_in_track_number]
enabled = true

[checks.invalid_track_or_disc_number]
enabled = true

[checks.album_tag]
enabled = true
ignore_folders = ["misc"]

[checks.album_artist]
enabled = true
remove_redundant = false
require_redundant = false

[checks.required_tags]
enabled = false
tags = ["artist", "title"]

[checks.single_value_tags]
enabled = true
tags = ["artist", "title"]

[checks.disc_numbering]
enabled = true
discs_in_separate_folders = false
disctotal_policy = "consistent"

[checks.track_numbering]
enabled = true
ignore_folders = ["misc"]
tracktotal_policy = "consistent"

[checks.track_title]
enabled = true

[checks.album_art]
enabled = true
cover_min_pixels = 100
cover_max_pixels = 2048
cover_squareness = 0.98
embedded_size_max = 8388608

[checks.front_cover_selection]
enabled = true
cover_required = false
unique = true

[checks.zero_pad_numbers]
enabled = true
tracknumber_pad = "two_digit_minimum"
tracktotal_pad = "two_digit_minimum"
discnumber_pad = "if_needed"
disctotal_pad = "never"

[checks.album_under_album]
enabled = true
