[locations]
# Music library root
# Default is OS-specific default user music folder e.g. ~/Music
library = "/path/to/music"

# Albums database file
# Default is OS-specific user storage e.g. ~/.config/albums/albums.db
database = "/path/to/albums.db"

# Extensions to scan (if the file type isn't supported by mutagen, there may be errors)
# Defaults to these extensions:
supported_file_types = [".flac", ".mp3", ".m4a", ".wma", ".ogg"]

[settings]
# Always rescan the media library before any operation (probably quite slow)
always_scan = false

[checks.album_tag]
# if a track doesn't have an ALBUM tag
enabled = true
# ignore this check when the album folder matches one of these names
ignore_folders = ["misc"]

[checks.album_under_album]
# if an album has another album in a subfolder
emabled = true

[checks.album_artist]
# if any tracks have different ARTIST tags, all tracks should have the same ALBUM ARTIST tag
# if any track has an ALBUM ARTIST tag, all tracks must have this tag
#
# Explanation: Many media players need the ALBUM ARTIST "albumartist" tag when the ARTIST is not
# the same on all tracks. Albums assumes a folder is an album so this should be consistent.
enabled = true
# if all tracks have the same ARTIST tag value, an ALBUM ARTIST tag might not be necessary:
remove_redundant = false
# even when all tracks have the same ARTIST tag value, an ALBUM ARTIST tag should also be present:
require_redundant = false

[checks.required_tags]
# all tracks should have one or more values for each of these tags
#
# Require certain tags for files that support common tag names.
enabled = true
tag_names = ["artist", "title"]

[checks.single_value_tags]
# if present, the specified tags should not have multiple values within the same track
#
# Explanation: It is valid for a track to have more than one title, but multiple-value tags may
# have unpredictable results in some media players. This check allows choosing one title or
# concatenating multiple titles into a single value.
enabled = true
tag_names = ["title", "tracknumber", "tracktotal"]
