[locations]
# Music library root
# Default is OS-specific default user music folder e.g. ~/Music
library = "/path/to/music"

# Albums database file
# Default is OS-specific user storage e.g. ~/.config/albums/albums.db
database = "/path/to/albums.db"

# Extensions to scan (if the file type isn't supported by mutagen, there may be errors)
# Defaults to these extensions:
supported_file_types = [ ".flac", ".mp3", ".m4a", ".wma", ".ogg" ]

[settings]
# Always rescan the media library before any operation (probably quite slow)
always_scan = false

[checks.album_under_album]
# if an album has another album in a subfolder
emabled = true

[checks.album_artist]
# if any tracks have different ARTIST tags, all tracks should have the same ALBUM ARTIST (or BAND) tag
# if any track has an ALBUM ARTIST or BAND tag, all tracks must have this tag
# if there is an ALBUM ARTIST tag there should not be a tag named BAND
enabled = true

[checks.required_tags]
# all tracks should have one or more values for each of these tags
enabled = true
tag_names = [ "artist", "title" ]

[checks.single_value_tags]
# if present, these tags should not have multiple values within the same track
enabled = true
tag_names = [ "album", "title", "tracknumber", "tracktotal" ]
