name: Publish Package
on:
  push:
    tags:
      - 'v*' # tags starting with 'v'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - uses: snok/install-poetry@v1
      - name: install dependencies
        run: make install
      - name: lint/analyze source
        run: make lint
      - name: run tests
        env:
          TERM: 'dumb'
        run: make test
      - name: create package
        run: make package
      - name: upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: albums-package
          path: dist/

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Use OIDC permissions for trusted publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: albums-package
          path: dist/
      - name: publish to pypi (test)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
